// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 8heT1pgrgbecLEwTnEku1h
// Component: hSDUh1u_5M6A

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: 8heT1pgrgbecLEwTnEku1h/projectcss
import sty from "./PlasmicCountdownNumber.module.css"; // plasmic-import: hSDUh1u_5M6A/css

createPlasmicElementProxy;

export type PlasmicCountdownNumber__VariantMembers = {};
export type PlasmicCountdownNumber__VariantsArgs = {};
type VariantPropType = keyof PlasmicCountdownNumber__VariantsArgs;
export const PlasmicCountdownNumber__VariantProps =
  new Array<VariantPropType>();

export type PlasmicCountdownNumber__ArgsType = {
  number?: React.ReactNode;
  unit?: React.ReactNode;
};
type ArgPropType = keyof PlasmicCountdownNumber__ArgsType;
export const PlasmicCountdownNumber__ArgProps = new Array<ArgPropType>(
  "number",
  "unit"
);

export type PlasmicCountdownNumber__OverridesType = {
  root?: Flex__<"div">;
};

export interface DefaultCountdownNumberProps {
  number?: React.ReactNode;
  unit?: React.ReactNode;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicCountdownNumber__RenderFunc(props: {
  variants: PlasmicCountdownNumber__VariantsArgs;
  args: PlasmicCountdownNumber__ArgsType;
  overrides: PlasmicCountdownNumber__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        sty.root
      )}
    >
      <div className={classNames(projectcss.all, sty.freeBox___9KaXw)}>
        {renderPlasmicSlot({
          defaultContents: "42",
          value: args.number,
          className: classNames(sty.slotTargetNumber)
        })}
      </div>
      <div className={classNames(projectcss.all, sty.freeBox__ccxs5)}>
        {renderPlasmicSlot({
          defaultContents: "Days",
          value: args.unit
        })}
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicCountdownNumber__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicCountdownNumber__VariantsArgs;
    args?: PlasmicCountdownNumber__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicCountdownNumber__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicCountdownNumber__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicCountdownNumber__ArgProps,
          internalVariantPropNames: PlasmicCountdownNumber__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicCountdownNumber__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicCountdownNumber";
  } else {
    func.displayName = `PlasmicCountdownNumber.${nodeName}`;
  }
  return func;
}

export const PlasmicCountdownNumber = Object.assign(
  // Top-level PlasmicCountdownNumber renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicCountdownNumber
    internalVariantProps: PlasmicCountdownNumber__VariantProps,
    internalArgProps: PlasmicCountdownNumber__ArgProps
  }
);

export default PlasmicCountdownNumber;
/* prettier-ignore-end */
